# Generated by Django 4.0.2 on 2024-08-18 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_tag_post_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slag',
            new_name='slug',
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='slag',
            new_name='slug',
        ),
    ]
