# Generated by Django 4.0.2 on 2024-08-20 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='image',
        ),
    ]
